### ISSUE TITLE
Precedence of \ vs ::

### ISSUE THREAD

**Issue by lambdacalculator** [abella-prover/abella#46]
Now, with higher-order context assumptions, shouldn't `\` get a higher precedence than `::`? I'm thinking of examples like

    Define ctx : olist -> prop by
      nabla x, (pi H\ hyp H x :: G) := ctx G.

which fails because `::` has a higher precedence than `\`, requiring you to add parentheses. Are there other, similarly prevalent examples I'm not recalling where the current precedence is to be preferred?

I realize that this example is now perhaps better written as a `Schema`, but I could add a non-`olist` argument to the definition, which arises quite commonly, where schemas can't be used (as least for now).

**Comment by chaudhuri** [comment]
Abella follows Lambda Prolog parsing rules for `\` which stipulates that the scope of the lambda expression is as far to the right as possible. This is unlikely to change, I think.

I'll keep this open if any of the other devs want to express an opinion.

**Comment by lambdacalculator** [comment]
The maximal scope rule for lambdas make sense, but what I'm suggesting is that the maximal scope of the lambda in my particular example ends at the `::`, because once we hit this operator, we are no longer in Lambda Prolog, but are in Abella.

**Comment by chaudhuri** [comment]
The issue is that Abella appropriates Lambda Prolog's &lambda;-term syntax for the reasoning level. With your proposal there would be no way to write a &lambda;-term of target type `olist` without parenthesizing the body.

Currently, `\` has the lowest precedence in the parser and `::` has the highest precedence. Swapping them seems risky, and would be a backwards-incompatible syntax change. Let me see what (if anything) breaks in the current store of examples.

Not sure which breaks the principle of least astonishment more -- the status quo or your proposed change.

**Comment by chaudhuri** [comment]
This change breaks many existing examples, so I am afraid it's too disruptive. None of the other devs seem overly supportive of making this change either. Please just use parentheses around your `pi`s.
