### ISSUE TITLE
Message on failed search

### ISSUE THREAD

**Issue by gisellemnr** [abella-prover/abella#55]
Sometimes search finishes very quickly and without success. It would be useful to get a message saying that no proof was found to avoid confusion with other situations when a proof was trivial and the next case is shown.

**Comment by lambdacalculator** [comment]
I just wanted to comment that I requested this behavior way back in March 2009, when Abella was being developed by @agacek for his PhD thesis; here was my question and his response at that time:

> > Speaking of error messages, shouldn't the "search" tactic give an error
> > message when it can't find anything?  Right now, it just echoes the same
> > proof state.
> 
> I can definitely see the argument for search giving an error when it
> fails. In fact, it does error when Abella is running in
> non-interactive mode (the -f flag). The reason why I didn't make it
> fail in interactive mode was that originally I was hoping to include
> tacticals in Abella. So you might do something like "case H3; search"
> and it would apply the search tactic to each subgoal which results
> from the case analysis. In this case, you don't want search to fail
> since that would trigger the whole tactical to fail. This is trying to
> mimic the behavior of Coq and its auto tactic. However, tacticals are
> not going to be put in anytime soon, so maybe search should be more
> verbose when it fails.

Perhaps this answer still applies now, but perhaps it doesn't. I just wanted to contribute this snippet of the history in case it helps.

**Comment by lambdacalculator** [comment]
To my previous comment, let me add two points:

- Even in the presence of tacticals, I still think it would make sense to give an error message when a _top-level_ search fails, even though the "silent" behavior is the most appropriate when search is being used as some part of a larger tactical, as in Andrew's example.
- One problem I've seen working with students is that a student's proof script might have a failed search in it that they forget to delete from their .thm file, which doesn't affect their eventually being able to complete the proof, but when they turn in the proof script to me, I can't run it non-interactively, because (as Andrew mentions), the search failure stops the non-interactive process.
