### ISSUE TITLE
No more Solutions

### ISSUE THREAD

**Issue by pramodcj** [abella-prover/abella#75]
Hi even adding the ~sr:!sr line in the abella.ml file of src directory of abella package. 
All the Query results say "No more Solutions." (attached screenshot)
This is even same for examples also.
please suggest the proper solution to get rid of this error.
Thank You in advance
![error](https://cloud.githubusercontent.com/assets/21186146/22395017/dcaed820-e4e5-11e6-8048-106a7daad894.png)

**Comment by chaudhuri** [comment]
It is not enough just to change `abella.ml`. You also have to recompile Abella.

Since you are using the Windows version, it may be a bit harder to recompile things. I've attached a newly compiled [`abella.exe`](http://abella-prover.org/distributions/abella-2.0.5-dev-20170130.exe) from the master branch.
