### ISSUE TITLE
No "Contexts don't match" error

### ISSUE THREAD

**Issue by lambdacalculator** [abella-prover/abella#78]
Attached minimal example that should produce "Contexts don't match" error, but apply is accepted.

[test.zip](https://github.com/abella-prover/abella/files/779343/test.zip)

**Comment by chaudhuri** [comment]
Thanks. This looks like a serious bug.

**Comment by chaudhuri** [comment]
Actually, wait, this is not a bug at all since `G` is not constrained in any way!

Basically, what Abella does is implicitly apply monotonicity to use, effectively, the equivalent of:

`apply apply IH to H4 H6 with G = (of n1 T2) :: (of n1 T1) :: G.`

If you had constrained the shape of `G` with a `ctx` definition, then you would not be able to do this because obviously this is not a well-formed context.

**Comment by lambdacalculator** [comment]
I see, thanks. Sorry for the false alarm!
